### ISSUE TITLE
Outdated article 

### ISSUE THREAD

**Issue by esimov** [rocketlaunchr/showerglass#4]
This is not related to the project itself, but to the article you are referring is a bit outdated. Is it possible to update it?

**Comment by pjebs** [comment]
What do you mean? Which part needs updating?

**Comment by pjebs** [comment]
https://github.com/golang/go/issues/52533

**Comment by esimov** [comment]
The code snippets are not adjusted to the latest Triangle package.

**Comment by pjebs** [comment]
I believe it is corrected now unless I missed something.

**Comment by pjebs** [comment]
@esimov I'll send you an email about an idea.

**Comment by esimov** [comment]
> @esimov I'll send you an email about an idea.

All right.

**Comment by pjebs** [comment]
@esimov Email sent
